### ISSUE TITLE
Tf2-automatic crashing

### ISSUE THREAD

**Issue by Hystericali** [Nicklason/tf2-automatic#100]
here's my issue 

15-02-2019 22:46:55 - debug: Attempting to connect to PM2...
15-02-2019 22:47:05 - debug: Successfully connected to PM2!
15-02-2019 22:47:05 - info: tf2-automatic v1.11.0 starting
15-02-2019 22:47:05 - info: Connecting to Steam...
15-02-2019 22:47:05 - error: tf2-automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.11.0; node: v10.15.1 win32 x64; Contact: null
crash: Stack trace:
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at new Hmac (internal/crypto/hash.js:88:11)
    at Object.createHmac (crypto.js:133:10)
    at Object.exports.generateAuthCode.exports.getAuthCode (C:\Users\Andrew\Desktop\tf2-automatic-master\tf2-automatic-master\node_modules\steam-totp\index.js:44:20)
    at C:\Users\Andrew\Desktop\tf2-automatic-master\tf2-automatic-master\app\login.js:23:48
    at IncomingMessage.res.on (C:\Users\Andrew\Desktop\tf2-automatic-master\tf2-automatic-master\node_modules\steam-totp\index.js:129:4)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
15-02-2019 22:47:05 - error: Create an issue here: https://github.com/Nicklason/tf2-automatic/issues/new
15-02-2019 22:50:36 - debug: Attempting to connect to PM2...
15-02-2019 22:50:37 - debug: Successfully connected to PM2!
15-02-2019 22:50:37 - info: tf2-automatic v1.11.0 starting
15-02-2019 22:50:37 - info: Connecting to Steam...
15-02-2019 22:50:37 - error: tf2-automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.11.0; node: v10.15.1 win32 x64; Contact: null
crash: Stack trace:
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at new Hmac (internal/crypto/hash.js:88:11)
    at Object.createHmac (crypto.js:133:10)
    at Object.exports.generateAuthCode.exports.getAuthCode (C:\Users\Andrew\Desktop\tf2-automatic-master\tf2-automatic-master\node_modules\steam-totp\index.js:44:20)
    at C:\Users\Andrew\Desktop\tf2-automatic-master\tf2-automatic-master\app\login.js:23:48
    at IncomingMessage.res.on (C:\Users\Andrew\Desktop\tf2-automatic-master\tf2-automatic-master\node_modules\steam-totp\index.js:129:4)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
15-02-2019 22:50:37 - error: Create an issue here: https://github.com/Nicklason/tf2-automatic/issues/new

I'm assuming i did something wrong any help would be great thanks

**Comment by Hystericali** [comment]
I fixed this problem issue on my end.
