### ISSUE TITLE
tf2-automatic crashed issue: Cannot read 'length' property

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#104]
09-04-2019 01:03:25 - error: tf2-automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.12.1; node: v10.15.2 win32 ia32; Contact: 76561198053911511
crash: Stack trace:
TypeError: Cannot read property 'length' of undefined
    at Schema.getName (C:\Users\Izzuddin\Documents\bot1_SmileBot\node_modules\tf2-items\lib\schema.js:230:40)
    at getName (C:\Users\Izzuddin\Documents\bot1_SmileBot\app\items.js:132:25)
    at Object.createDictionary (C:\Users\Izzuddin\Documents\bot1_SmileBot\app\items.js:58:20)
    at C:\Users\Izzuddin\Documents\bot1_SmileBot\app\inventory.js:104:34
    at C:\Users\Izzuddin\Documents\bot1_SmileBot\app\inventory.js:63:9
    at SteamCommunity.<anonymous> (C:\Users\Izzuddin\Documents\bot1_SmileBot\node_modules\steamcommunity\components\users.js:484:5)
    at Request._callback (C:\Users\Izzuddin\Documents\bot1_SmileBot\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\Izzuddin\Documents\bot1_SmileBot\node_modules\steamcommunity\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Users\Izzuddin\Documents\bot1_SmileBot\node_modules\steamcommunity\node_modules\request\request.js:1161:10)
09-04-2019 01:03:25 - error: Create an issue here: https://github.com/Nicklason/tf2-automatic/issues/new
Press any key to continue . . .

**Comment by Nicklason** [comment]
Delete the schema.json file from the temp folder and restart the bot, that will fix it.

**Comment by idinium96** [comment]
Thank you @Nicklason , I've deleted schema.json file and the error is gone, but new error just appeared:

09-04-2019 01:13:31 - error: An error occurred while initializing the packages: tf2-items (ETIMEDOUT).
Press any key to continue . . .

Please help.. I don't know why this happened.

**Comment by Nicklason** [comment]
That's a temporary error, just try running it again

**Comment by idinium96** [comment]
Thank you! Problem solved :)
