### ISSUE TITLE
What happened here?

### ISSUE THREAD

**Issue by woahtechnolagy** [Nicklason/tf2-automatic#134]
20/06/2019 07:06:00 - error: tf2-automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.12.2; node: v10.16.0 win32 x64; Contact: null
crash: Stack trace:
Error: Cannot log onto steamcommunity.com without first being connected to Steam network
    at SteamUser.webLogOn (C:\Program Files\Tf2Automatic\tf2-automatic\node_modules\steam-user\components\web.js:10:9)
    at Object.refreshSession (C:\Program Files\Tf2Automatic\tf2-automatic\app\automatic.js:104:30)
    at C:\Program Files\Tf2Automatic\tf2-automatic\app\trade.js:1189:27
    at Object.exports.makeAnError (C:\Program Files\Tf2Automatic\tf2-automatic\node_modules\steam-tradeoffer-manager\lib\helpers.js:50:4)
    at SteamCommunity.manager._community.httpRequestGet (C:\Program Files\Tf2Automatic\tf2-automatic\node_modules\steam-tradeoffer-manager\lib\classes\TradeOffer.js:607:13)
    at Request._callback (C:\Program Files\Tf2Automatic\tf2-automatic\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Program Files\Tf2Automatic\tf2-automatic\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Program Files\Tf2Automatic\tf2-automatic\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)

**Comment by Nicklason** [comment]
This should be a temporary error that happens when Steam is down
