### ISSUE TITLE
Crashed! I have deleted the scheme.json file but the same message appeared.

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#137]
14-10-2019 21:10:20 - error: tf2-automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.12.3; node: v11.9.0 win32 x64; Contact: 76561198053911511
crash: Stack trace:
TypeError: Cannot read property 'Tokens' of undefined
    at Request.request (F:\tf2bot\bot1_SmileBot\node_modules\tf2-items\lib\schema.js:281:45)
    at Request._callback (F:\tf2bot\bot1_SmileBot\node_modules\lodash\lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (F:\tf2bot\bot1_SmileBot\node_modules\@nicklason\request-retry\node_modules\requestretry\index.js:105:19)
    at Request.<anonymous> (F:\tf2bot\bot1_SmileBot\node_modules\@nicklason\request-retry\node_modules\requestretry\index.js:146:10)
    at Request.self.callback (F:\tf2bot\bot1_SmileBot\node_modules\request\request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (F:\tf2bot\bot1_SmileBot\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:197:13)
    at Gunzip.<anonymous> (F:\tf2bot\bot1_SmileBot\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)

**Comment by Nicklason** [comment]
Fixed https://github.com/Nicklason/tf2-automatic/releases/tag/v1.12.4

**Comment by idinium96** [comment]
$ git pull                                                                       
remote: Enumerating objects: 9, done.                                            
remote: Counting objects: 100% (9/9), done.                                      
remote: Compressing objects: 100% (8/8), done.                                   
remote: Total 9 (delta 3), reused 4 (delta 1), pack-reused 0                     
Unpacking objects: 100% (9/9), done.                                             
From https://github.com/Nicklason/tf2-automatic                                     
884aad4..6d4aee3  master     -> origin/master                                  
* [new tag]         v1.12.4    -> v1.12.4                                       
**error: Your local changes to the following files would be overwritten by merge: package-lock.json                                                        
Please commit your changes or stash them before you merge.**                       
Aborting                                                                         
Updating 884aad4..6d4aee3
--

Do I need to delete that file?

**Comment by Nicklason** [comment]
Just do `git reset HEAD --hard` and then `git pull`

**Comment by idinium96** [comment]
I have reset it and do as you instructed, and the error message like this appeared:

14-10-2019 23:22:49 - info: tf2-automatic v1.12.4 starting
14-10-2019 23:22:49 - info: Connecting to Steam...
14-10-2019 23:22:55 - error: tf2-automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.12.4; node: v11.9.0 win32 x64; Contact: 76561198053911511
crash: Stack trace:
TypeError: Cannot read property 'Tokens' of undefined
    at Request.request (F:\tf2bot\bot1_SmileBot\node_modules\tf2-items\lib\schema.js:281:45)
    at Request._callback (F:\tf2bot\bot1_SmileBot\node_modules\lodash\lodash.js:10052:25)
    at Request.requestRetryReply [as reply] (F:\tf2bot\bot1_SmileBot\node_modules\@nicklason\request-retry\node_modules\requestretry\index.js:105:19)
    at Request.<anonymous> (F:\tf2bot\bot1_SmileBot\node_modules\@nicklason\request-retry\node_modules\requestretry\index.js:146:10)
    at Request.self.callback (F:\tf2bot\bot1_SmileBot\node_modules\request\request.js:185:22)
    at Request.emit (events.js:197:13)
    at Request.<anonymous> (F:\tf2bot\bot1_SmileBot\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:197:13)
    at Gunzip.<anonymous> (F:\tf2bot\bot1_SmileBot\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:285:13)
14-10-2019 23:22:55 - error: Create an issue here: https://github.com/Nicklason/tf2-automatic/issues/new
Press any key to continue . . .

**Comment by idinium96** [comment]
I am currently trying to reinstall it and just copy and paste the temp folder, and if possible, the trade log.

**Comment by Nicklason** [comment]
You need to update the modules

**Comment by idinium96** [comment]
It's ok. It just works as normal again after I reinstalled it. Thank you very much for your help and update Sir! :)
