### ISSUE TITLE
Bot crashes on start

### ISSUE THREAD

**Issue by ShamanCoder** [Nicklason/tf2-automatic#169]
Bot crashes on first start. Followed the instruction on installation(all required commands issued). Failed on the first step of configuration tutorial. Can't start the bot with "node app.js" in both windows command terminal and PowerShell. When run, gives an error.

`PS D:\tf-automatic> node app.js                                                                                         
D:\tf-automatic\app\handler-manager.js:156
            throw new Error('Missing required environment variable "' + optName.slice(6).toLowerCase().replace(/_/g, '"'));
            ^

Error: Missing required environment variable "account"name
    at D:\tf-automatic\app\handler-manager.js:156:19
    at Array.forEach (<anonymous>)
    at checkEnv (D:\tf-automatic\app\handler-manager.js:154:19)
    at Object.exports.setup (D:\tf-automatic\app\handler-manager.js:131:5)
    at Object.<anonymous> (D:\tf-automatic\app.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)`

System info : Intel Core i5-4460 3.20GHz RAM 8GB Windows 10 Pro, all updates installed

**Comment by HackerinoS2** [comment]
You need to create a file called ".env", and copy paste the data from "template.env" to the ".env" file. Then you fill your account details.

**Comment by Gobot1234** [comment]
You haven't set up the .env file correctly

**Comment by ShamanCoder** [comment]
> You need to create a file called ".env", and copy paste the data from "template.env" to the ".env" file. Then you fill your account details.

Now it works, but it also gives an error. I suppose it is because my account in new and requires to wait a week for trading to become unlimited.

`PS D:\tf-automatic> node app.js
2020-01-04 22:36:21 info: tf2-automatic v2.3.0 is starting...
2020-01-04 22:36:21 info: Signing in to Steam...
2020-01-04 22:36:23 info: Signed in to Steam!
2020-01-04 22:36:23 verbose: Checking account limitations...
2020-01-04 22:36:23 error: tf2-automatic crashed! Please create an issue with the following log:
package.version: 2.3.0; node: v12.14.0 win32 x64}
Stack trace:
Error: The account is limited
    at D:\tf-automatic\app.js:222:29
    at SteamUser.accountLimitationsEvent (D:\tf-automatic\app\utils\limitationsCallback.js:26:9)
    at Object.onceWrapper (events.js:300:26)
    at SteamUser.emit (events.js:210:5)
    at SteamUser.<anonymous> (D:\tf-automatic\node_modules\steam-user\components\account.js:164:7)
    at D:\tf-automatic\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (D:\tf-automatic\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (D:\tf-automatic\node_modules\steam-user\components\messages.js:543:24)
    at SteamUser._handleNetMessage (D:\tf-automatic\node_modules\steam-user\components\messages.js:478:7)
2020-01-04 22:36:23 error: Create an issue here: https://github.com/Nicklason/bot-framework/issues/new
2020-01-04 22:36:23 warn: Exiting...`

**Comment by Nicklason** [comment]
You need to add a $5 to the account if you haven’t already, please read https://support.steampowered.com/kb_article.php?ref=3330-iagk-7663

**Comment by Nicklason** [comment]
Closing issue
