### ISSUE TITLE
Polldata gets corrupted

### ISSUE THREAD

**Issue by Waflson** [Nicklason/tf2-automatic#171]
2020-01-06 06:38:08 info: tf2-automatic v2.5.0 is starting...
2020-01-06 06:38:08 error: tf2-automatic crashed! Please create an issue with the following log:
package.version: 2.5.0; node: v10.18.0 linux x64}
Stack trace:
SyntaxError: Unexpected number in JSON at position 82318
    at JSON.parse (<anonymous>)
    at /root/Waflson/app/utils/files.js:38:27
    at /root/Waflson/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
2020-01-06 06:38:08 error: Create an issue here: https://github.com/Nicklason/bot-framework/issues/new
2020-01-06 06:38:08 warn: Exiting...

**Comment by Waflson** [comment]
*might not be related* but here is the error before the corruption.
TypeError: Cannot read property 'our' of undefined
    at TradeOffer.module.exports [as summarize] (/root/Waflson/app/utils/offer/summarize.js:14:68)
    at /root/Waflson/app/handler/trades.js:759:64
    at /root/Waflson/app/utils/isBanned.js:17:16
    at err (/root/Waflson/node_modules/async/dist/async.js:2959:19)
    at wrapper (/root/Waflson/node_modules/async/dist/async.js:272:20)
    at iterateeCallback (/root/Waflson/node_modules/async/dist/async.js:425:28)
    at /root/Waflson/node_modules/async/dist/async.js:325:20
    at result (/root/Waflson/node_modules/async/dist/async.js:2957:17)
    at Request.<anonymous> (/root/Waflson/app/utils/isBanned.js:54:16)
    at Request._callback (/root/Waflson/node_modules/lodash/lodash.js:10050:25

**Comment by Nicklason** [comment]
The error has been fixed, hopefully this fixes the polldata corruption.
