### ISSUE TITLE
Strangifers in user's backpack causing crash that does not restart bot. 

### ISSUE THREAD

**Issue by Waflson** [Nicklason/tf2-automatic#179]
Bot crashes when someone with the 'Camera Beard Strangifier' attempts to initiate a trade using chat commands. 
Bot also does not kill itself after error.

Error: Could not find target for item "Camera Beard Strangifier"
    at getTarget (/root/Waflson/app/utils/item/getItem.js:277:15)
    at CEconItem.module.exports [as getItem] (/root/Waflson/app/utils/item/getItem.js:27:23)
    at CEconItem.module.exports [as getSKU] (/root/Waflson/app/utils/item/getSKU.js:4:23)
    at Object.exports.createDictionary (/root/Waflson/app/inventory.js:245:26)
    at /root/Waflson/app/inventory.js:62:39
    at /root/Waflson/app/inventory.js:29:9
    at SteamCommunity.<anonymous> (/root/Waflson/node_modules/steamcommunity/components/users.js:491:5)
    at Request._callback (/root/Waflson/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/root/Waflson/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)

**Comment by Waflson** [comment]
```
"message":"Message from Azu (76561198046479972): !sell 1 Taunt: The High Five!","level":"info","timestamp":"2020-01-11T10:25:02.241Z"}
{"steamid":"76561198046479972","sku":"167;6","amount":1,"buying":true,"time":1578738302,"level":"debug","message":"Adding requested offer to the queue","timestamp":"2020-01-11T10:25:02.245Z"}
{"message":"tf2-automatic crashed! Please create an issue with the following log:\r\npackage.version: 2.7.0; node: v10.18.0 linux x64}\r\nStack trace:\r\nError: Could not find target for item \"Ghastly Gibus Strangifier\"\n    at getTarget (/root/Waflson/app/utils/item/getItem.js:277:15)\n    at CEconItem.module.exports [as getItem] (/root/Waflson/app/utils/item/getItem.js:27:23)\n    at CEconItem.module.exports [as getSKU] (/root/Waflson/app/utils/item/getSKU.js:4:23)\n    at Object.exports.createDictionary (/root/Waflson/app/inventory.js:245:26)\n    at /root/Waflson/app/inventory.js:62:39\n    at /root/Waflson/app/inventory.js:29:9\n    at SteamCommunity.<anonymous> (/root/Waflson/node_modules/steamcommunity/components/users.js:491:5)\n    at Request._callback (/root/Waflson/node_modules/steamcommunity/components/http.js:67:15)\n    at Request.self.callback (/root/Waflson/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:198:13)","level":"error","timestamp":"2020-01-11T10:25:03.175Z"}
{"message":"Create an issue here: https://github.com/Nicklason/bot-framework/issues/new","level":"error","timestamp":"2020-01-11T10:25:03.175Z"}
{"err":{},"level":"debug","message":"Shutdown has been initialized, stopping...","timestamp":"2020-01-11T10:25:03.176Z"}
{"message":"Cleaning up","level":"debug","timestamp":"2020-01-11T10:25:03.176Z"}
{"event":"disconnect","from":"socket.io-client","reason":"io  up","level":"debug","timestamp":"2020-01-11T10:25:03.176Z"}
{"event":"disconnect","from":"socket.io-client","reason":"io client disconnect","level":"debug","message":"Disconnected from socket server","timestamp":"2020-01-11T10:25:03.189Z"}
{"event":"debug","from":"steam-tradeoffer-manager","level":"debug","message":"Error getting trade offers for poll: socket hang up","timestamp":"2020-01-11T10:30:47.369Z"}
```

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/981051cb92f4d9cd61309088f333ea4d2550dd3a
