### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by aethezxd** [Nicklason/tf2-automatic#201]
TypeError: callback is not a function
at doneCheckingAll (/home/pi/Desktop/bot/bot2/app/handler/listings.js:155:17)
at Timeout.<anonymous> (/home/pi/Desktop/bot/bot2/app/handler/listings.js:119:28)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)

**Comment by Nicklason** [comment]
Have you modified the bot? I don't see why it would say that the callback is not a function.

**Comment by aethezxd** [comment]
I mean yes, could just be my shit.

**Comment by Nicklason** [comment]
@aethezxd For your auto-bump script, give the function a callback function.
