### ISSUE TITLE
Crashing when trade offer sent manually

### ISSUE THREAD

**Issue by Mark7888** [Nicklason/tf2-automatic#310]
**Describe the bug**

When i sent a trade offer from the bots account manually, the bot just simply crashed. So i stimulated it again and again, so i'm really sure about that, this maight be a bug.

**To Reproduce**

1. Start the bot.
2. Send a trade offer from the trade bot's account manually while it's running.
3. When the offer is accepted, the bot will crash out.

**Expected behavior**
The bot could be ignore all the sent offers, and just dont crash

**Screenshots and logs**
```
error: tf2-automatic crashed! Please create an issue with the following log:
package.version: 3.1.0; node: v10.19.0 linux arm}
Stack trace:
TypeError: Cannot read property 'our' of undefined
    at TradeOffer.module.exports [as getDiff] (/home/pi/tf2-automatic/dist/lib/extend/offer/getDiff.js:9:28)
    at bot.inventoryManager.getInventory.fetch.asCallback (/home/pi/tf2-automatic/dist/classes/Trades.js:520:32)
    at tryCatcher (/home/pi/tf2-automatic/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/pi/tf2-automatic/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/home/pi/tf2-automatic/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/home/pi/tf2-automatic/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/pi/tf2-automatic/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/pi/tf2-automatic/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/pi/tf2-automatic/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/pi/tf2-automatic/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/pi/tf2-automatic/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
**Additional context**

Version: 
3.1.0

**Comment by CubityFirst** [comment]
Can't reproduce this.

I sent an offer from the bot account, the bot saw the offer, and decided to cancel it (as expected).

**Comment by Mark7888** [comment]
Any time I do it, it crashes with that error message... :/
