### ISSUE TITLE
Could not get account limitations

### ISSUE THREAD

**Issue by eprosync** [Nicklason/tf2-automatic#320]
2020-02-24 11:21:57 verbose: Checking account limitations...

Error: Could not get account limitations
    at Timeout.setTimeout [as _onTimeout] (/home/blanked/tf2-automatic/dist/classes/Bot.js:367:31)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
2020-02-24 11:22:07 error: tf2-automatic failed to start properly, this is most likely a temporary error. See the log:
package.version: 3.1.0; node: v8.9.0 linux arm}
Stack trace:
Error: Could not get account limitations
    at Timeout.setTimeout [as _onTimeout] (/home/blanked/tf2-automatic/dist/classes/Bot.js:367:31)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
2020-02-24 11:22:07 warn: Exiting...

**Comment by Nicklason** [comment]
You can disable this in the config. I am pretty sure it tells you that before it starts doing the checks.
