### ISSUE TITLE
PM2 pidusage error spam

### ISSUE THREAD

**Issue by kebaburmum** [Nicklason/tf2-automatic#360]
**Describe the bug**

Its probably just me, but wheneve I run the bot I get lots of messages about the same error. It maybe has to do something with wmic as I saw online. 

PM2              | Error caught while calling pidusage
PM2              | Error: Error: spawn wmic ENOENT
PM2              |     at ChildProcess.<anonymous> (C:\Users\herni\AppData\Roaming\npm\node_modules\pm2\node_modules\pidusage\lib\bin.js:33:10)
PM2              |     at ChildProcess.emit (events.js:321:20)
PM2              |     at ChildProcess.EventEmitter.emit (domain.js:485:12)
PM2              |     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
PM2              |     at onErrorNT (internal/child_process.js:467:16)
PM2              |     at processTicksAndRejections (internal/process/task_queues.js:84:21)

**To Reproduce**

1. ... 
2. ...
3. ...

**Expected behavior**

**Screenshots and logs**

https://gyazo.com/357d3125916766aa766e111fde1963ff

**Additional context**

Version: 3.3.3

**Comment by kebaburmum** [comment]
I´ve just uploaded the directory to VPS, seems like the error is not present there anymore. Still im leaving this open if you want to look at it
