### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by philipho10** [Nicklason/tf2-automatic#363]
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lalito\AppData\Roaming\npm-cache\_logs\2020-03-05T00_12_04_277Z-debug.log

C:\Users\lalito\Documents\GitHub\tf2-automatic>

i can't start the bot for this problem, helpp

**Comment by idinium96** [comment]
Please ensure you've done all the steps in the wiki.
https://github.com/Nicklason/tf2-automatic/wiki/Installation
https://github.com/Nicklason/tf2-automatic/wiki/Configuration
https://github.com/Nicklason/tf2-automatic/wiki/Running-the-bot

Also, ensure the `template.env` file is saved as `.env`, not as `.env.env` or etc.

**Comment by philipho10** [comment]
i do

**Comment by idinium96** [comment]
Can you give the screenshot of your tf2-automatic folder?

**Comment by philipho10** [comment]
sure
![aaaaaaaaaa](https://user-images.githubusercontent.com/61202882/75936766-dd8c0080-5e61-11ea-93c4-ad91ec64e9a3.png)

**Comment by idinium96** [comment]
What's that `tf2-automatic.env` file? 🤔

Enable "Show file extensions" and rename it `.env`
https://www.file-extensions.org/article/show-and-hide-file-extensions-in-windows-10

**Comment by philipho10** [comment]
ready but still not working

**Comment by idinium96** [comment]
Try run the bot using `node dist/app.js` in cmd.

**Comment by philipho10** [comment]
aah, i dont have pm2, I had to use another form of configuration for pm2 and I thought it worked

**Comment by idinium96** [comment]
https://github.com/Nicklason/tf2-automatic/wiki/PM2

**Comment by philipho10** [comment]
when i use pm2 startup dont work, [PM2][ERROR] Init system not found
C:\Users\Julian\AppData\Roaming\npm\node_modules\pm2\lib\API\Startup.js:210
      throw new Error('Init system not found');

**Comment by idinium96** [comment]
Please read.
![read](https://user-images.githubusercontent.com/47635037/75941132-d7316f00-5ec9-11ea-9ff2-2f6ef7c8cf14.PNG)

**Comment by philipho10** [comment]
aah, i have windows :(

**Comment by philipho10** [comment]
i can't use the bot?

**Comment by philipho10** [comment]
you can help me with this??

**Comment by philipho10** [comment]
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at new Bot (C:\Users\Julian\Desktop\tf2-automatic\dist\classes\Bot.js:74:72)
    at C:\Users\Julian\Desktop\tf2-automatic\dist\classes\BotManager.js:75:32
    at C:\Users\Julian\Desktop\tf2-automatic\dist\classes\BotManager.js:83:17
    at C:\Users\Julian\Desktop\tf2-automatic\node_modules\async\dist\async.js:2159:44
    at replenish (C:\Users\Julian\Desktop\tf2-automatic\node_modules\async\dist\async.js:445:21)
    at iterateeCallback (C:\Users\Julian\Desktop\tf2-automatic\node_modules\async\dist\async.js:429:21)
    at C:\Users\Julian\Desktop\tf2-automatic\node_modules\async\dist\async.js:326:20
    at tryCatcher (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\nodeify.js:22:30)
    at Promise._settlePromise (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Julian\Desktop\tf2-automatic\node_modules\bluebird\js\release\async.js:102:5)

**Comment by idinium96** [comment]
Not sure.

**Comment by idinium96** [comment]
Ensure the `"ALERTS":` in ecosystem.json file is set in an array.
If you want to enable notification on accepted trades:
`"ALERTS": ["trade"],`
If not:
`"ALERTS": ["none"],`

**Comment by philipho10** [comment]
when I tried to change it it was already set to none

**Comment by philipho10** [comment]
i found first syntax error in "STEAM_PASSWORD": "..........",",
but still have more errors

**Comment by Nicklason** [comment]
GitHub is for bugs and feature requests only, not for help setting up the bot. If you need help setting up the bot then just follow the wiki, if you still need help then you can ask in the discord server.
