### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by NguyenMcRuo** [Nicklason/tf2-automatic#394]
**Describe the bug**
Cannot get past "Signing in to Steam..." phase, as there appears to be a problem with a Steam guard. What am I missing?

2020-03-18 00:46:34 info: Getting TF2 schema...
2020-03-18 00:46:35 info: Starting bot...
2020-03-18 00:46:35 info: Setting up pricelist...
2020-03-18 00:46:35 info: Signing in to Steam...
2020-03-18 00:46:38 error: tf2-automatic failed to start properly, this is most likely a temporary error. See the log:
package.version: 3.3.10; node: v13.9.0 win32 x64}
Stack trace:
Error: Too many wrong Steam Guard codes
    at Bot.onSteamGuard (C:\Users\Admin\Desktop\tf2-automatic\dist\classes\Bot.js:546:19)
    at Immediate.<anonymous> (C:\Users\Admin\Desktop\tf2-automatic\dist\classes\Bot.js:134:21)
    at processImmediate (internal/timers.js:456:21)
2020-03-18 00:46:38 warn: Exiting...

Version: 3.3.10

**Comment by idinium96** [comment]
Please check whether you filled in `STEAM_SHARED_SECRET` and `STEAM_IDENTITY_SECRET` correctly in your `.env` or `ecosystem.json` file, then try again.
If it persists after you've done the above step, try again another time. Steam might down.

**Comment by NguyenMcRuo** [comment]
Will do, thanks.
