### ISSUE TITLE
Bot is unable to check escrow and thus can't handle trade offers - malformed response

### ISSUE THREAD

**Issue by ShamanCoder** [Nicklason/tf2-automatic#468]
**Expected behavior:**
Bot should process the trade offer and make a decision to either accept or decline it.

**Actual behavior:**
Bot tries to check escrow and fails, making the trade impossible to handle, thus the trade is left unprocessed.

Here is the log:
```
{"message":"Checking` account info","level":"debug","timestamp":"2020-11-01T01:04:33.577Z"}
{"message":"Offer #4281376741 from 76561198382555244 received offer","level":"info","timestamp":"2020-11-01T01:04:57.029Z"}
{"message":"Added offer to queue","level":"debug","timestamp":"2020-11-01T01:04:57.034Z"}
{"message":"Only offer in queue, process it","level":"debug","timestamp":"2020-11-01T01:04:57.035Z"}
{"message":"Giving offer to handler","level":"debug","timestamp":"2020-11-01T01:04:57.035Z"}
{"message":"Offer #4281376741 from 76561198382555244 is being processed...","level":"info","timestamp":"2020-11-01T01:04:57.039Z"}
{"message":"Offer #4281376741 from 76561198382555244 checking escrow...","level":"info","timestamp":"2020-11-01T01:04:57.054Z"}
{"message":"Checking escrow","level":"debug","timestamp":"2020-11-01T01:04:57.057Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:04:57.059Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:04:57.948Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:04:59.837Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:05:00.921Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:05:04.457Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:05:05.010Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:05:12.032Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:05:13.000Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:05:23.471Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:05:24.004Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:05:48.629Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:05:49.126Z"}
{"level":"warn","message":"Failed to check escrow: Malformed response","stack":"Error: Malformed response\n    at SteamCommunity.<anonymous> (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:732:24)\n    at Request._callback (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/steamcommunity/components/http.js:67:15)\n    at Request.self.callback (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:314:20)\n    at Request.<anonymous> (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:314:20)\n    at Gunzip.<anonymous> (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:420:28)\n    at Gunzip.emit (events.js:314:20)\n    at endReadableNT (_stream_readable.js:1244:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","timestamp":"2020-11-01T01:05:49.131Z"}
{"message":"Offer #4281376741 from 76561198382555244 handler is done with offer","level":"debug","timestamp":"2020-11-01T01:05:49.136Z"}
{"message":"Processing next offer","level":"debug","timestamp":"2020-11-01T01:05:49.138Z"}
{"message":"Already processing offer or queue is empty","level":"debug","timestamp":"2020-11-01T01:05:49.139Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-11-01T01:06:03.552Z"}
{"message":"2 incoming offers (0 on hold), 0 outgoing offers (0 on hold)","level":"verbose","timestamp":"2020-11-01T01:06:05.596Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-11-01T01:07:33.573Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-11-01T01:09:03.584Z"}
{"message":"2 incoming offers (0 on hold), 0 outgoing offers (0 on hold)","level":"verbose","timestamp":"2020-11-01T01:09:13.265Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-11-01T01:10:33.565Z"}
{"message":"Offer #4281381964 from 76561198382555244 received offer","level":"info","timestamp":"2020-11-01T01:11:57.288Z"}
{"message":"Added offer to queue","level":"debug","timestamp":"2020-11-01T01:11:57.293Z"}
{"message":"Only offer in queue, process it","level":"debug","timestamp":"2020-11-01T01:11:57.294Z"}
{"message":"Giving offer to handler","level":"debug","timestamp":"2020-11-01T01:11:57.294Z"}
{"message":"Offer #4281381964 from 76561198382555244 is being processed...","level":"info","timestamp":"2020-11-01T01:11:57.298Z"}
{"message":"Offer #4281381964 from 76561198382555244 checking escrow...","level":"info","timestamp":"2020-11-01T01:11:57.313Z"}
{"message":"Checking escrow","level":"debug","timestamp":"2020-11-01T01:11:57.315Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:11:57.317Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:11:57.896Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:11:59.727Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:12:00.343Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:12:02.794Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:12:03.391Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-11-01T01:12:03.578Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:12:09.495Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:12:10.185Z"}
{"message":"3 incoming offers (0 on hold), 0 outgoing offers (0 on hold)","level":"verbose","timestamp":"2020-11-01T01:12:16.694Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:12:25.677Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:12:26.467Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-11-01T01:12:54.217Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-11-01T01:12:54.699Z"}
{"level":"warn","message":"Failed to check escrow: Malformed response","stack":"Error: Malformed response\n    at SteamCommunity.<anonymous> (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/steam-tradeoffer-manager/lib/classes/TradeOffer.js:732:24)\n    at Request._callback (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/steamcommunity/components/http.js:67:15)\n    at Request.self.callback (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:314:20)\n    at Request.<anonymous> (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:314:20)\n    at Gunzip.<anonymous> (/storage/emulated/0/soft/Utils/tf2-automatic/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:420:28)\n    at Gunzip.emit (events.js:314:20)\n    at endReadableNT (_stream_readable.js:1244:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","timestamp":"2020-11-01T01:12:54.703Z"}
{"message":"Offer #4281381964 from 76561198382555244 handler is done with offer","level":"debug","timestamp":"2020-11-01T01:12:54.708Z"}
{"message":"Processing next offer","level":"debug","timestamp":"2020-11-01T01:12:54.709Z"}
{"message":"Already processing offer or queue is empty","level":"debug","timestamp":"2020-11-01T01:12:54.710Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-11-01T01:13:33.599Z"}
```

**Context:**
Running the bot on a phone using Termux, have compiled code on PC. Half a month ago a bot was compiled and run the same way, but it was working successfully. Changed my Steam Guard, so I had to wait 15 days. All the new steam secrets were added to the config. The bot was reinstalled cleanly, all the new steam secrets were added to the config. I shut down the bot with '!stop'.

_Version: 3.5.2_

**Comment by idinium96** [comment]
Most of the dependencies for tf2-automatic are outdated, and one of them is `steamcommunity`.

Update `steamcommunity` by running `npm i steamcommunity --save` and restart your bot.

If you want to update any other dependencies, run `npm outdated` and it will list out all other outdated dependencies. You can update each of them with the same command mentioned above, or multiple with `npm i <dep1> [dep2] ... [depN] --save`. Please avoid updating `@types/death` and `jsonschema` dependencies as the newer version do not compatible with the current tf2-automatic source codes.

**Comment by ShamanCoder** [comment]
Updated all dependencies except for @types/death and @jsonschema with `npm i [dependency] --save`.
This didn't affect my bot at all, it still gives the same error.

**Comment by ShamanCoder** [comment]
Sorry for my improper testing, I forgot to test on my computer.
Interestingly, the bot works on my PC, so it's not a problem with a bot.
I suppose I'll look into it for a few more days.

**Comment by ShamanCoder** [comment]
I tried to install tf2-automatic on my phone a compile it there too.
During `npm install` I've found out that my phone can't create symlinks. This is probably related to my storage being formatted in fat and not ext4. I'll try to get an SD card on which I would install the bot on.

**Comment by ShamanCoder** [comment]
I was able to set the bot up on my phone this way:
1. Go to `/data/media/0/` (Important: not `/sdcard/` or `/storage/emulated/0/` - the bot's setup requires creating symbolic links which are only supported on ext4 and most phones have their emulated storage formatted using exfat, so use `/data/media/0/ because it magically supports symlinks on all phones).
2. Follow the instructions from the wiki.
3. Update the npm modules using `npm i [module_name] (This also is important - tried starting the bot without updating modules and it just gave me the same errors as before).
4. Set up the configuration file using the help of the wiki.
5. Start the bot.
6. Profit! 👍
