### ISSUE TITLE
bot cannot started

### ISSUE THREAD

**Issue by skeezjoo** [Nicklason/tf2-automatic#477]
node dist/app.js
2021-03-01 13:39:51 warn: You are not running the bot with PM2! If the bot crash
es it won't start again, see the documentation: https://github.com/Nicklason/tf2
-automatic/wiki/PM2
2021-03-01 13:39:54 error: tf2-automatic failed to start properly, this is most
likely a temporary error. See the log:
package.version: 3.5.2; node: v14.16.0 win32 x64}
Stack trace:
Error: Missing required environment variable "STEAM_ACCOUNT_NAME"
    at C:\Users\silen\OneDrive\Рабочий стол\tf2 bot\tf2-automatic\dist\classes\B
otManager.js:61:35
    at Array.forEach (<anonymous>)
    at C:\Users\silen\OneDrive\Рабочий стол\tf2 bot\tf2-automatic\dist\classes\B
otManager.js:59:27
    at Promise._execute (C:\Users\silen\OneDrive\Рабочий стол\tf2 bot\tf2-automa
tic\node_modules\bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\silen\OneDrive\Рабочий стол\tf2 bo
t\tf2-automatic\node_modules\bluebird\js\release\promise.js:518:18)
    at new Promise (C:\Users\silen\OneDrive\Рабочий стол\tf2 bot\tf2-automatic\n
ode_modules\bluebird\js\release\promise.js:103:10)
    at BotManager.start (C:\Users\silen\OneDrive\Рабочий стол\tf2 bot\tf2-automa
tic\dist\classes\BotManager.js:58:16)
    at Object.<anonymous> (C:\Users\silen\OneDrive\Рабочий стол\tf2 bot\tf2-auto
matic\dist\app.js:84:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:72:12)
    at internal/main/run_main_module.js:17:47
2021-03-01 13:39:54 warn: Exiting...

Screen: https://imgur.com/a/MOsG4hX

**Comment by Gobot1234** [comment]
See https://github.com/Nicklason/tf2-automatic/wiki/Errors#missing-required-enviroment-variable

**Comment by skeezjoo** [comment]
I don’t have polldata.json and I don’t have a files folder

**Comment by skeezjoo** [comment]
thanks, everything worked
