### ISSUE TITLE
Tf2 automatic crash

### ISSUE THREAD

**Issue by Mark7888** [Nicklason/tf2-automatic#53]
crash: Automatic.version: 1.7.29; node: v10.9.0 win32 x64; Contact: 76561198856342890
crash: Stack trace:
TypeError: Cannot read property 'def_index' of undefined
    at getDefindex (C:\Users\acer\Desktop\bot\tf2 automatic\app\offer.js:204:45)
    at Function.getItem (C:\Users\acer\Desktop\bot\tf2 automatic\app\offer.js:57:23)
    at Object.createDictionary (C:\Users\acer\Desktop\bot\tf2 automatic\app\items.js:44:28)
    at updateOrders (C:\Users\acer\Desktop\bot\tf2 automatic\app\backpacktf.js:223:51)
    at Timeout._onTimeout (C:\Users\acer\Desktop\bot\tf2 automatic\app\backpacktf.js:216:9)
    at ontimeout (timers.js:424:11)
    at tryOnTimeout (timers.js:288:5)
    at listOnTimeout (timers.js:251:5)
    at Timer.processTimers (timers.js:211:10)

**Comment by Nicklason** [comment]
This error is very rare, nothing to be done about it right now
