### ISSUE TITLE
File must be non empty?

### ISSUE THREAD

**Issue by ZeusJunior** [Nicklason/tf2-automatic#69]
2|automati | crash: Automatic.version: 1.10.6; node: v8.10.0 linux x64; Contact: 76561198176024095
2|automati | crash: Stack trace:
2|automati | TypeError: "file" argument must be a non-empty string
2|automati |     at normalizeSpawnArguments (child_process.js:383:11)
2|automati |     at Object.exports.spawn (child_process.js:496:38)
2|automati |     at Function.spawn (/root/tf2-automatic/node_modules/cross-spawn/index.js:87:19)
2|automati |     at spawnPhantom (/root/tf2-automatic/node_modules/webshot/lib/webshot.js:201:32)
2|automati |     at spawn (/root/tf2-automatic/node_modules/webshot/lib/webshot.js:105:14)
2|automati |     at /root/tf2-automatic/node_modules/webshot/lib/webshot.js:117:16
2|automati |     at FSReqWrap.cb [as oncomplete] (fs.js:312:19)

**Comment by ZeusJunior** [comment]
Screenshot error, nvm
