### ISSUE TITLE
utils.second is not a function

### ISSUE THREAD

**Issue by kebaburmum** [Nicklason/tf2-automatic#71]
17:04:39 - error: backpack.tf Automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.3.3; node: v10.11.0 win32 x64; Contact: 76561198866655074
crash: Stack trace::
TypeError: utils.seconds is not a function
    at removeOldOffers (C:\Users\herni\Desktop\sandvich\app\trade.js:1356:27)
    at TradeOfferManager.savePollData (C:\Users\herni\Desktop\sandvich\app\trade.js:1345:16)
    at TradeOfferManager.emit (events.js:182:13)
    at getOffers (C:\Users\herni\Desktop\sandvich\node_modules\steam-tradeoffer-manager\lib\polling.js:268:9)
    at Helpers.checkNeededDescriptions (C:\Users\herni\Desktop\sandvich\node_modules\steam-tradeoffer-manager\lib\index.js:500:4)
    at Async.map (C:\Users\herni\Desktop\sandvich\node_modules\steam-tradeoffer-manager\lib\assets.js:171:4)
    at C:\Users\herni\Desktop\sandvich\node_modules\steam-tradeoffer-manager\node_modules\async\dist\async.js:1140:9
    at C:\Users\herni\Desktop\sandvich\node_modules\steam-tradeoffer-manager\node_modules\async\dist\async.js:473:16
    at iteratorCallback (C:\Users\herni\Desktop\sandvich\node_modules\steam-tradeoffer-manager\node_modules\async\dist\async.js:1064:13)
    at C:\Users\herni\Desktop\sandvich\node_modules\steam-tradeoffer-manager\node_modules\async\dist\async.js:969:16
17:04:39 - error: Create an issue here: https://bitbucket.org/jessecar/backpack.tf-automatic/issues/new
Press any key to continue . . .

I have coppied only trade.js and all the moduls needed, any help?

**Comment by Nicklason** [comment]
This is not the place to ask for help about bptf automatic
